### ISSUE TITLE
js 代码片段未生效

### ISSUE THREAD

**Issue by ghost** [XuanmiaoG/hexo-baidu-url-push#2]
- 这样把 js 代码片段嵌入页面中是有问题的
- 下面以我的某个页面为例

```
<ol>
<li>在某环境中安装 Python 包时要使用 <code>conda</code> 命令或者 <code>pip</code> 命令</li>
<li><code>base</code> 为基础环境，Anaconda 安装完成后自动产生</li>
<li>其他配置好的环境位置：<code>C:\ProgramData\Anaconda3\envs</code>（以默认安装位置为例）<script><br>(function(){<br> var bp = document.createElement('script');<br> var curProtocol = window.location.protocol.split(':')[0];<br> if (curProtocol === 'https') {<br> bp.src = '<a target="_blank" rel="noopener" href="https://zz.bdstatic.com/linksubmit/push.js&#39;">https://zz.bdstatic.com/linksubmit/push.js&#39;</a>;<br> }<br> else {<br> bp.src = '<a target="_blank" rel="noopener" href="http://push.zhanzhang.baidu.com/push.js&#39;">http://push.zhanzhang.baidu.com/push.js&#39;</a>;<br> }<br> var s = document.getElementsByTagName("script")[0];<br> s.parentNode.insertBefore(bp, s);<br>})();<br></script></li>
</ol>
```
- 虽然生成页面的时候没报错，但是仔细观察就会发现，这个 js 代码片段根本没有生效

**Comment by ghost** [comment]
百度好像取消了js自动推送的接口了，百度站长平台收录中也没这个选项了

**Comment by XuanmiaoG** [comment]
The code was refactored to use the Injector function and remove the reander function.
重构了代码，使用了injector功能，删去了render功能，scripts代码片段放置于<head>标签开头之后。 
[https://hexo.io/zh-cn/api/injector](injector)  
![image](https://user-images.githubusercontent.com/25542819/157006592-424d8e19-41a3-4bb7-ba87-2941c2dc3c44.png)

```javascripts
var fs = require('fs');
hexo.extend.injector.register('head_begin',function(push){
var push = fs.readFileSync('./node_modules/hexo-baidu-url-push/push.js');
return push;});
```

**Comment by XuanmiaoG** [comment]
> 百度好像取消了js自动推送的接口了，百度站长平台收录中也没这个选项了

注意到百度推送功能在站长平台消失了，但https://zz.bdstatic.com/linksubmit/push.js， http://push.zhanzhang.baidu.com/push.js两个script中的链接依然存在。
百度自动推送功能在2020年3月份下线，又在2020年9月份重新上线
>尊敬的搜索合作伙伴：
您好，即日起搜索资源平台恢复“普通收录-自动推送”功能，以便更快发现与收录站点新增资源，降低站点维护成本。特别提醒，自动推送仅对已关联主体的站点开放。感谢您的关注与支持!
发现12月份有一封自动推送下线的公告
看来只能使用api推送了

**Comment by XuanmiaoG** [comment]
有可能只能使用另外一个插件 [hexo-baidu-url-submit](https://github.com/huiwang/hexo-baidu-url-submit)

**Comment by ghost** [comment]
- hexo-baidu-url-submit 只有在部署博客的时候才会提交 urls
- 改进的话可以通过 GitHub Actions 设置定时任务，每天定时提交 urls 给百度
